openapi: 3.0.0
info:
  description: "API documentation for the Team Beetle Stage 3 Task on the Backend Track"
  version: "1.0.0"
  title: "Team Beetle Boilerplate API documentation"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
  - name: "Authentication"
    description: "Authentication related endpoints"
  - name: "user"
    description: "Operations about user"
  - name: "Organization"
    description: "Operations about organizations"
  - name: "Payments"
    description: "Payment related endpoints"
  - name: "Admin"
    description: "Superadmin operations"
  - name: "Misc"
    description: "Miscellaneous operations"
paths:
  # Authentication
  /auth/login:
    $ref: "./paths/auth.yaml#login"
  /auth/register:
    $ref: "./paths/auth.yaml#register"
  /auth/social:
    $ref: "./paths/auth.yaml#register"
  /auth/magic-link:
    $ref: "./paths/auth.yaml#magic-link"
  /auth/change-password:
    $ref: "./paths/auth.yaml#change-password"
  /auth/logout:
    $ref: "./paths/auth.yaml#logout"

  # Email
  /email/send:
    $ref: "./paths/email.yaml#send"
  /email/templates:
    $ref: "./paths/email.yaml#templates"

  # Payments
  /payments:
    $ref: "./paths/payments.yaml#payments"

  /payments/{paymentId}:
    $ref: "./paths/payments.yaml#paymentsById"
  # /payments/flutterwave:
  #   $ref: './paths/payments.yaml#flutterwave'
  # /payments/lemonsqueezy:
  #   $ref: './paths/payments.yaml#lemonsqueezy'
  # /payments/:
  #   $ref: './paths/payments.yaml#payments'

definitions:
  Login:
    $ref: "./schemas/schemas.yaml#Login"
  Register:
    $ref: "./schemas/schemas.yaml#Register"
externalDocs:
  description: "Find out more about our API"
  url: "https://github.com/daviduzondu/team_beetle_hng_boilerplate_node_web/tree/main"
