userId:
  name: userId
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: The unique identifier of the user

organizationId:
  name: organizationId
  in: path
  required: true
  schema:
    type: string
    format: uuid
  description: The unique identifier of the organization

pagination:
  - name: page
    in: query
    schema:
      type: integer
      minimum: 1
      default: 1
    description: The page number for pagination
  - name: limit
    in: query
    schema:
      type: integer
      minimum: 1
      maximum: 100
      default: 20
    description: The number of items per page

sortOrder:
  name: sort
  in: query
  schema:
    type: string
    enum: [asc, desc]
    default: asc
  description: The sort order for the returned items
